export default {
    store:{
        "/admin/user":[
            'rolePhone',
            'roleStaffName'
        ],
        "/baseInfo/employer":[
            'baseEmployerStaffNumber',
            'baseEmployerStaffName',
            'baseEmployerMobile',
			'baseEmployerEnterprise',
        ],
        "/salaryManage/dealDownload":[
            'dealDownloadStaffNumber',
            'dealDownloadStaffName',
            'dealDownloadMinMoney',
            'dealDownloadMaxMoney',
			'dealDownloadDepartment',
			'dealDownloadEnterprise'
        ],
        "/salaryManage/dealConfirm":[
            'dealConfirmStaffNumber',
            'dealConfirmStaffName',
            'dealConfirmMinMoney',
            'dealConfirmMaxMoney',
			'dealConfirmEnterprise'
        ],
        "/profit/autoWithdraw":[
            'autoStaffNumber',
            'autoStaffName',
            'autoOption',
			'autoEnterprise'
        ],
        "/query/multipleQuery":[
            'mQueryStaffNumber',
            'mQueryType',
            'mQueryDate',
            'mQueryStaffType',
            'mQueryDateSec',
			'mQueryEnterprise'
        ],
        "/query/employerQuery":[
            'eQueryStaffNumber',
            'eQueryStaffName',
            'eQueryMinMoney',
            'eQueryMaxMoney',
			'eQueryEnterprise'
        ],
		"/salaryManage/salaryProvide":[
			'saProvideEnterprise',
		],
		"/query/summaryQuery":[
			'sumQDate1',
			'sumQDate2',
			'sumQEnterprise'
		]
    }
}